# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!(name:  "Demo User", email: "demo@email.com", password:"demopassword")

Category.create!(name: "Sneakers", description: "On StockY, every sneaker you want is always available and authentic. Buy and sell new sneakers & shoes from Air Jordan, adidas, Nike, Yeezy and more!")

Product.create!(name: "New Balance 550", style: "BB550ALE", color: "WHITE", price: 130.0, brand: "New Balance", image: "https://images.stockx.com/images/New-Balance-550-Aime-Leon-Dore-White-Grey-1.png?fit=fill&bg=FFFFFF&w=480&h=320&fm=avif&auto=compress&q=90&dpr=1&trim=color&updated_at=1607668787", description: "Aimè Leon Dore teamed up with New Balance to bring back the New Balance 550, a low-top basketball silhouette originally introduced in 1989 as the New Balance P550.", release_date: Date.parse('2020-08-20'), seller_id: 2, category_id: 1)

Product.create!(name: "Air Force 1 Low 07", style: "315122-111/CW2288-111", color: "WHITE", price: 90.0, brand: "Nike", image: "https://images.stockx.com/360/Nike-Air-Force-1-Low-White-07/Images/Nike-Air-Force-1-Low-White-07/Lv2/img01.jpg?fm=avif&auto=compress&w=480&q=90&dpr=2&updated_at=1635275427", description: "The Nike Air Force 1 Low White 07 features an all-white leather upper with a perforated toe box and Swoosh overlays. A Nike heel embroidery and white sole completes the design.", release_date: Date.parse('2016-08-20'), seller_id: 2, category_id: 1)

Product.create!(name: "Yeezy Boost 350 V2", style: "HQ6316", color: "BONE", price: 230.0, brand: "Adidas", image: "https://images.stockx.com/360/adidas-Yeezy-Boost-350-V2-Pure-Oat/Images/adidas-Yeezy-Boost-350-V2-Pure-Oat/Lv2/img01.jpg?fm=avif&auto=compress&w=480&q=90&dpr=2&updated_at=1648479649", description: "The adidas Yeezy Boost 350 V2 Bone features a triple white Primeknit upper with mesh side stripes and canvas heel tabs. At the base, a semi-translucent sole with Boost technology completes the design.", release_date: Date.parse('2022-03-21'), seller_id: 2, category_id: 1)

Product.create!(name: "Jordan 4 Retro", style: "CT8527-700", color: "YELLOW", price: 220.0, brand: "Jordan", image: "https://images.stockx.com/360/Air-Jordan-4-Retro-Lightning-2021/Images/Air-Jordan-4-Retro-Lightning-2021/Lv2/img01.jpg?fm=avif&auto=compress&w=480&q=90&dpr=2&updated_at=1638476062", description: "Originally released in 2006, the Air Jordan 4 Retro Lightning (2021) is one of the most renowned retro Jordan 4 colorways in Jordan Brand's catalog. It features a Tour Yellow Durabuck upper with black netted panels and dark grey eyelets.", release_date: Date.parse('2021-03-21'), seller_id: 2, category_id: 1)

Product.create!(name: "Yeezy Boost 700", style: "GW0296", color: "WASH ORANGE", price: 240.0, brand: "Adidas", image: "https://images.stockx.com/360/adidas-Yeezy-Boost-700-Wash-Orange/Images/adidas-Yeezy-Boost-700-Wash-Orange/Lv2/img01.jpg?fm=avif&auto=compress&w=480&q=90&dpr=2&updated_at=1635732395", description: "The adidas Yeezy Boost 700 Wash Orange features a grey leather, suede, and mesh upper with teal panels and reflective underlays. At the base, a thick Wash Orange Boost midsole contrasts cool tones found in the upper.", release_date: Date.parse('2021-10-21'), seller_id: 2, category_id: 1)

Product.create!(name: "SB Dunk Low Pro", style: "DH7695-600", color: "FIRE PINK", price: 110.0, brand: "Nike", image: "https://images.stockx.com/360/Nike-SB-Dunk-Low-Parra-2021/Images/Nike-SB-Dunk-Low-Parra-2021/Lv2/img01.jpg?fm=avif&auto=compress&w=480&q=90&dpr=2&updated_at=1635254176", description: "Nike and Dutch artist and sneaker collab veteran Parra teamed up for an Olympic inspired Nike SB Dunk Low with the Nike SB Dunk Low Parra Abstract Art.", release_date: Date.parse('2021-07-31'), seller_id: 2, category_id: 1)

Product.create!(name: "Air Force 1 Low", style: "CN2405-900", color: "MULTI-COLOR", price: 160.0, brand: "Nike", image: "https://images.stockx.com/360/Nike-Air-Force-1-Low-Travis-Scott-Cactus-Jack/Images/Nike-Air-Force-1-Low-Travis-Scott-Cactus-Jack/Lv2/img01.jpg?fm=avif&auto=compress&w=480&q=90&dpr=2&updated_at=1635276243", description: "Travis Scott and Nike add a new design to their growing Air Force arsenal with the Air Force 1 Low Travis Scott Cactus Jack, now available on StockX.", release_date: Date.parse('2019-07-31'), seller_id: 2, category_id: 1)

Product.create!(name: "Air Force 1 Low", style: "AQ4211-101", color: "SAIL", price: 150.0, brand: "Nike", image: "https://images.stockx.com/360/Nike-Air-Force-1-Low-Travis-Scott-Sail/Images/Nike-Air-Force-1-Low-Travis-Scott-Sail/Lv2/img01.jpg?fm=avif&auto=compress&w=480&q=90&dpr=2&updated_at=1635252948", description: "With Astroworld upon us, its about time Cactus Jack blessed us with a new pair of kicks too. This time, Nike boy Travis Scott linked up with the Swoosh on another colorway of the Air Force 1 Low silhouette.", release_date: Date.parse('2018-08-10'), seller_id: 2, category_id: 1)